workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - when: never

stages:
  - build

build:
  stage: build
  tags:
    - saas-linux-small-amd64
  image: eclipse-temurin:21-jdk
  script:
    - chmod +x ./mvnw
    - ./mvnw clean package
  artifacts:
    paths:
      - ./target/*.jar
